// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-pages/CryptoTerminal.tsx": () => import("../components/mockups/landing-pages/CryptoTerminal.tsx"),
  "./components/mockups/landing-pages/NeonCasino.tsx": () => import("../components/mockups/landing-pages/NeonCasino.tsx"),
  "./components/mockups/landing-pages/VipHighRoller.tsx": () => import("../components/mockups/landing-pages/VipHighRoller.tsx")
};
